dia=input("dime un dia").upper()
match dia:
    case"LUNES":
        print("=============================")
        print("=============================")
        print("            LUNES            ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("8-9 FOL"                      )
        print("9-10 LENGUAJE DE MARCAS"          ) 
        print("10-11 LENGUAJE DE MARCAS"         )  
        print("11-11:30 RECREO"                  )
        print("11:30-12:30 SISTEMAS INFORMATICOS")
        print("12:30- 1:30 SISTEMAS INFORMATICOS")
        print("1:30-2:30 ENTORNO"                )
        print("=============================")
    case"MARTES":
        print("=============================")
        print("=============================")
        print("            MARTES           ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("8-9 FOL"                      )
        print("9-10 LENGUAJE DE MARCAS"          ) 
        print("10-11 LENGUAJE DE MARCAS"         )  
        print("11-11:30 RECREO"                  )
        print("11:30-12:30 SISTEMAS INFORMATICOS")
        print("12:30- 1:30 SISTEMAS INFORMATICOS")
        print("1:30-2:30 ENTORNO"                )
        print("=============================")
    case"MIERCOLES":
        print("=============================")
        print("=============================")
        print("          MIERCOLES          ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("8-9 FOL"                      )
        print("9-10 LENGUAJE DE MARCAS"          ) 
        print("10-11 LENGUAJE DE MARCAS"         )  
        print("11-11:30 RECREO"                  )
        print("11:30-12:30 SISTEMAS INFORMATICOS")
        print("12:30- 1:30 SISTEMAS INFORMATICOS")
        print("1:30-2:30 ENTORNO"                )
        print("=============================")
    case"JUEVES":
        print("=============================")
        print("=============================")
        print("           JUEVES            ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("8-9 FOL"                      )
        print("9-10 LENGUAJE DE MARCAS"          ) 
        print("10-11 LENGUAJE DE MARCAS"         )  
        print("11-11:30 RECREO"                  )
        print("11:30-12:30 SISTEMAS INFORMATICOS")
        print("12:30- 1:30 SISTEMAS INFORMATICOS")
        print("1:30-2:30 ENTORNO"                )
        print("=============================")
    case"VIERNES":
        print("=============================")
        print("=============================")
        print("            LUNES            ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("8-9 FOL"                      )
        print("9-10 LENGUAJE DE MARCAS"          ) 
        print("10-11 LENGUAJE DE MARCAS"         )  
        print("11-11:30 RECREO"                  )
        print("11:30-12:30 SISTEMAS INFORMATICOS")
        print("12:30- 1:30 SISTEMAS INFORMATICOS")
        print("1:30-2:30 ENTORNO"                )
        print("=============================")
    case"SABADO":
        print("=============================")
        print("=============================")
        print("           SABADO            ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("DESCANSAR"                    )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("=============================")
    case"DOMINGO":
        print("=============================")
        print("=============================")
        print("          DOMINGO            ")
        print("                             ")
        print("=============================")
        print("=============================")
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("DESCANSAR"                      )
        print("=============================")

        

